services:
  sentiment-api:
    build:
      context: ./DOCKER/sentiment-api
      dockerfile: Dockerfile
    container_name: my-container
    ports:
      - "8000:8000"
    environment:
      - PTYHONUNBUFFERED=1
    networks:
      - new-network

networks:
  new-network:
    driver: bridge